services:
  # App
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: "Host(`api.${DOMAIN}`)"
      traefik.http.routers.api.entrypoints: "web"
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    labels:
      traefik.enable: true
      traefik.http.routers.web.rule: "Host(`${DOMAIN}`)"
      traefik.http.routers.web.entrypoints: "web"

  # Infra
  db:
    image: postgres:latest
  proxy:
    image: traefik:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
