services:
  db:
    image: docker.io/library/postgres:18.4-trixie
    # Passwordは各環境向けcomposeで設定する

  proxy:
    image: docker.io/library/traefik:3.7.4
    command:
      # 引数は各環境向けcomposeで設定する
      - "--help"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
    labels:
      traefik.enable: true
      traefik.http.routers.proxy.rule: "Host(`proxy.localhost`)"
      traefik.http.routers.proxy.entrypoints: web
      traefik.http.routers.proxy.service: api@internal

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    labels:
      traefik.enable: true
      traefik.http.routers.app.rule: "Host(`app.localhost`)"
      traefik.http.routers.app.entrypoints: web
