name: my-devenv-recipe-testing
services:
  adminer:
    image: docker.io/library/adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    labels:
      traefik.enable: true
      traefik.http.routers.adminer.rule: "Host(`db-admin.localhost`)"

  whoami:
    image: docker.io/traefik/whoami:latest
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: "Host(`whoami.localhost`)"

  proxy:
    command: 
      - "--api=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`com.docker.compose.project`,`my-devenv-recipe-testing`)"
