name: my-devenv-recipe-dev-${WORKTREE_SLUG}

networks:
  default:
    external: true
    name: my-devenv-recipe-dev_default

services:
  dev:
    build:
      context: docker/dev
      dockerfile: Dockerfile
    command: sleep infinity
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${WORKTREE_SLUG}.rule=Host(`api-${WORKTREE_SLUG}.${DOMAIN}`)"
      - "traefik.http.routers.${WORKTREE_SLUG}.entrypoints=web"
      - "traefik.http.routers.${WORKTREE_SLUG}.service=${WORKTREE_SLUG}"
      - "traefik.http.services.${WORKTREE_SLUG}.loadbalancer.server.port=8000"
      - "traefik.http.routers.web-${WORKTREE_SLUG}.rule=Host(`${WORKTREE_SLUG}.${DOMAIN}`)"
      - "traefik.http.routers.web-${WORKTREE_SLUG}.entrypoints=web"
      - "traefik.http.routers.web-${WORKTREE_SLUG}.service=web-${WORKTREE_SLUG}"
      - "traefik.http.services.web-${WORKTREE_SLUG}.loadbalancer.server.port=3000"
    volumes:
      - .:/workspace/my-devenv-recipe:cached
      - ${MAIN_REPO_ROOT}/.git:${MAIN_REPO_ROOT}/.git
