services:
  dev:
    build:
      context: .devcontainer
      dockerfile: dev.Dockerfile
      args:
        USERNAME: developer
    command: [ "sleep", "infinity" ]
    volumes:
      - .:/workspace:cached
      - ${HOME}/.gitconfig:/home/developer/.gitconfig:ro
      - ${HOME}/.claude:/home/developer/.claude:cached
    environment:
      XDG_CACHE_HOME: /workspace/.devcontainer/.cache
  db:
    environment:
      POSTGRES_PASSWORD: password

  app: !reset null
